server:
  port: 8081
  servlet:
    context-path: /boot

spring:
  application:
    name: project
#日志
logging:
  file:
    path: /app/teamwork/log/project/${spring.application.name}.log
  level:
    root: error
    com:
      teamwork: debug
