server:
  port: 8081
  servlet:
    context-path: /boot

spring:
  application:
    name: project
##日志
#logging:
#  file: /app/pms/log/contract/${spring.application.name}.log
#  #TRACE < DEBUG < INFO < WARN < ERROR < FATAL
#  level:
#    root: error
#    com:
#      infoepoch: debug

api:
  name: 小红
  url-map:
    baidu: https://www.baidu.com/
    project: http://localhost:8081/boot/user/test
