server:
  port: 8081
  servlet:
    context-path: /app/teamwork

spring:
  application:
    name: project
  profiles:
    active: dev
#  cloud:
#    stream:
#      bindings:
#        accountEvent:
#          destination: account-event
#          content-type: application/json
#      rocketmq:
#        binder:
#          name-server: 47.240.68.6:9876
#        bindings:
#          roleData:
#            consumer:
#              orderly: true
#          accountEvent:
#            producer:
#              group: ${spring.application.name}
#              sync: true
#              vipChannelEnabled: false
#  #              transactional: true
#日志
logging:
  file:
    path: /app/teamwork/log/project/${spring.application.name}.log
  level:
    root: error
    com:
      teamwork: debug
